-- Clear existing data and populate comprehensive website content for search functionality
DELETE FROM website_content;

-- Home Page Content
INSERT INTO website_content (page_title, page_url, content_type, heading, description, keywords) VALUES
('Home', '/', 'hero', 'Engineering Excellence', 'LSEA Corporation provides comprehensive engineering solutions across multiple disciplines', ARRAY['engineering', 'excellence', 'civil', 'structural', 'consulting']),
('Home', '/', 'services_section', 'Our Services', 'We provide comprehensive engineering solutions across multiple disciplines. Our team of experienced professionals delivers innovative, cost-effective solutions that meet the highest industry standards. From conceptual design to project completion, we ensure excellence in every phase of your project.', ARRAY['engineering', 'solutions', 'professionals', 'innovative', 'cost-effective', 'design', 'construction']),
('Home', '/', 'culture_section', 'Our Culture', 'At LSEA, we foster a collaborative environment where innovation thrives. Our team-oriented culture promotes continuous learning, professional growth, and mutual respect. We believe that great engineering comes from great teamwork, and we''re committed to creating an inclusive workplace where every voice is heard and valued.', ARRAY['culture', 'collaborative', 'innovation', 'teamwork', 'learning', 'professional growth', 'inclusive']),
('Home', '/', 'offices_section', 'Our Offices', 'With strategically located offices across multiple states, we''re positioned to serve clients wherever their needs arise. Our regional presence allows us to understand local regulations, infrastructure requirements, and construction standards while maintaining the consistency and quality standards that define LSEA Corporation.', ARRAY['offices', 'multiple states', 'regional', 'local regulations', 'infrastructure', 'quality standards']),

-- About Page Content
('About', '/about', 'hero', 'About Us', 'Learn about LSEA Corporation''s history, mission, expertise and commitment to engineering excellence', ARRAY['about', 'history', 'mission', 'expertise', 'commitment']),
('About', '/about', 'our_story', 'Our Story', 'LSEA Corporation is a multi-discipline consulting firm established in 2001 with a vision to provide exceptional engineering and consulting services to both public and private sector clients. Founded by a small team of dedicated professionals, our company has steadily grown through a commitment to quality, innovation, and client satisfaction. We offer a comprehensive range of services, including bridge inspection, bridge design and rehabilitation, building assessment, building design and rehabilitation, architecture, MEP engineering, site and highway engineering, land surveying, structural assessment and design, and traffic engineering. Each project we undertake is approached with technical rigor, attention to detail, and a focus on long-term value. Since our founding, we have successfully completed hundreds of projects—from small-scale residential developments to large infrastructure installations. These projects have contributed to a deep and diverse knowledge base that informs our approach to engineering excellence. Today, LSEA Corporation continues to expand its capabilities while maintaining the personalized service and high standards that have defined us from the beginning.', ARRAY['established 2001', 'consulting firm', 'public sector', 'private sector', 'bridge inspection', 'bridge design', 'rehabilitation', 'building assessment', 'architecture', 'MEP engineering', 'highway engineering', 'land surveying', 'structural assessment', 'traffic engineering', 'infrastructure']),
('About', '/about', 'company_mission', 'Company Mission', 'At LSEA Corporation, our mission is to deliver innovative engineering solutions that exceed client expectations while upholding the highest standards of quality, safety, and environmental responsibility. We are committed to creating sustainable, efficient, and safe outcomes that positively impact communities and contribute to a better future. We believe that successful engineering goes beyond project completion—it''s about building lasting relationships through integrity, excellence, and continuous improvement. Through close collaboration with our clients, we work to understand their unique challenges and deliver tailored solutions that provide both immediate results and long-term value. Our dedicated team of highly qualified and motivated professionals is the foundation of our success. By combining technical expertise with personalized service, we are able to match the capabilities of larger firms while maintaining the responsiveness and attention to detail that define our approach. At LSEA, our success is measured by the success of our clients and the meaningful contributions our work makes to society.', ARRAY['mission', 'innovative solutions', 'quality', 'safety', 'environmental responsibility', 'sustainable', 'communities', 'integrity', 'excellence', 'collaboration', 'technical expertise', 'personalized service']),
('About', '/about', 'technical_expertise', 'Technical Expertise', 'LSEA Corporation offers a multidisciplinary team with expertise in civil and structural engineering. With decades of combined experience, our principals, project managers, and engineers are equipped to manage projects of various sizes and complexities. From preliminary studies to final design, we provide the technical support and insight needed to complement our clients'' in-house teams and deliver fully integrated solutions. Our engineers bring specialized knowledge in seismic design, sustainable building practices, advanced materials, and complex system integration. We leverage cutting-edge technology and proven methodologies to develop solutions that are both innovative and practical. At LSEA, we take a comprehensive, holistic approach to engineering—considering every aspect of a project from concept through implementation. This perspective allows us to identify challenges early, streamline project delivery, and optimize performance, efficiency, and cost-effectiveness. Through continuous learning and professional development, our team remains at the forefront of industry advancement, ensuring our clients benefit from the latest in engineering innovation.', ARRAY['multidisciplinary', 'civil engineering', 'structural engineering', 'project managers', 'seismic design', 'sustainable building', 'advanced materials', 'system integration', 'cutting-edge technology', 'holistic approach', 'professional development']),
('About', '/about', 'certifications', 'Total Commitment and Qualifications', 'At LSEA Corporation, our success is built on the expertise and dedication of our experienced staff. With a multidisciplinary team of professionals in civil, structural, mechanical, and electrical engineering, we deliver innovative, practical solutions tailored to each client''s needs. From feasibility studies to final design, we manage projects of all sizes and complexity with a commitment to quality, budget, and schedule. We invest heavily in continued education, training, licensing, and certifications to ensure our staff remains at the forefront of industry standards and technology. This ongoing development enables us to deliver high-performance solutions that meet today''s engineering challenges. LSEA is proud to be certified as a Minority Business Enterprise (MBE), Disadvantaged Business Enterprise (DBE), and Small Business Enterprise (SBE) with over 20 public agencies. MBE certifications include Port Authority of NY & NJ, NJDOT, NJ Transit, NYS Dept. of Economic Development, NJ Turnpike Authority, NYCSCA. DBE certifications include NJDOT, NYSDOT, NJ Transit, MTA (NYC Transit, LIRR, Metro-North, Bridges & Tunnels). SBE certifications include NJDOT, NJ Turnpike Authority, Delaware River Port Authority. At LSEA, we combine technical excellence with personal commitment—ensuring every project is completed to the highest standards of safety, sustainability, and client satisfaction.', ARRAY['experienced staff', 'mechanical engineering', 'electrical engineering', 'feasibility studies', 'continued education', 'training', 'licensing', 'certifications', 'MBE', 'DBE', 'SBE', 'Port Authority', 'NJDOT', 'NJ Transit', 'NYSDOT', 'MTA', 'NYC Transit', 'LIRR', 'Metro-North', 'technical excellence', 'sustainability']),

-- Services Page Content
('Services', '/services', 'hero', 'Our Services', 'Comprehensive engineering services across multiple disciplines and specializations', ARRAY['services', 'engineering', 'disciplines', 'specializations']),
('Services', '/services', 'bridge_inspection', 'Bridge Inspection', 'Professional bridge inspection services ensuring safety and compliance with industry standards', ARRAY['bridge inspection', 'safety', 'compliance', 'industry standards']),
('Services', '/services', 'bridge_design', 'Bridge Design and Rehabilitation', 'Expert bridge design and rehabilitation services for infrastructure projects', ARRAY['bridge design', 'rehabilitation', 'infrastructure projects']),
('Services', '/services', 'building_assessment', 'Building Assessment', 'Comprehensive building assessment and evaluation services', ARRAY['building assessment', 'evaluation', 'structural analysis']),
('Services', '/services', 'building_design', 'Building Design and Rehabilitation', 'Complete building design and rehabilitation solutions', ARRAY['building design', 'rehabilitation', 'construction']),
('Services', '/services', 'architecture', 'Architecture', 'Architectural design and planning services for various project types', ARRAY['architecture', 'architectural design', 'planning']),
('Services', '/services', 'mep_engineering', 'MEP Engineering', 'Mechanical, Electrical, and Plumbing engineering services', ARRAY['MEP engineering', 'mechanical', 'electrical', 'plumbing']),
('Services', '/services', 'highway_engineering', 'Site and Highway Engineering', 'Site development and highway engineering solutions', ARRAY['site engineering', 'highway engineering', 'development']),
('Services', '/services', 'land_surveying', 'Land Surveying', 'Professional land surveying and mapping services', ARRAY['land surveying', 'mapping', 'surveying']),
('Services', '/services', 'structural_assessment', 'Structural Assessment and Design', 'Structural engineering assessment and design services', ARRAY['structural assessment', 'structural design', 'engineering']),
('Services', '/services', 'traffic_engineering', 'Traffic Engineering', 'Traffic engineering and transportation planning services', ARRAY['traffic engineering', 'transportation planning', 'traffic analysis']),

-- Portfolio Page Content with Project Details
('Portfolio', '/portfolio', 'hero', 'Our Portfolio', 'Showcasing our engineering projects and achievements across various sectors', ARRAY['portfolio', 'projects', 'achievements', 'engineering']),
('Portfolio', '/portfolio', 'project', 'Overhead Sign Inspections (2016)', 'LSEA provided sign inspection services to the NJDOT for 106 state-owned overhead sign structures along various routes throughout New Jersey.', ARRAY['overhead sign inspection', 'NJDOT', 'sign structures', 'New Jersey', 'state-owned']),
('Portfolio', '/portfolio', 'project', 'Passaic County Bridge Inspections (2012-2013)', 'LSEA performed inspections and calculated load ratings for 55 Passaic County owned bridges as part of a two cycle agreement.', ARRAY['Passaic County', 'bridge inspections', 'load ratings', 'county bridges']),
('Portfolio', '/portfolio', 'project', 'NJTA – GSP North and South (2005, 2008, 2009, 2017, and 2018)', 'In 2017 and 2018, NJTA selected LSEA as a prime consultant to inspect over 250 bridges along the Garden State Parkway.', ARRAY['NJTA', 'Garden State Parkway', 'GSP', 'bridge inspection', 'prime consultant']),
('Portfolio', '/portfolio', 'project', 'NJTA – Microwave Tower Inspection (2014 and 2017)', 'LSEA inspected 15 cell towers in 2014 and 24 cell towers in 2017.', ARRAY['NJTA', 'microwave tower', 'cell towers', 'tower inspection']),
('Portfolio', '/portfolio', 'project', 'DRPA/PATCO Threat & Vulnerability Assessment (2016)', 'LSEA conducted a threat & vulnerability assessment for the properties owned and operated by the DRPA-PATCO.', ARRAY['DRPA', 'PATCO', 'threat assessment', 'vulnerability assessment']),
('Portfolio', '/portfolio', 'project', 'Walt Whitman Bridge Biennial Inspection (2008, 2010 and 2012)', 'LSEA, as a sub-consultant, performed a biennial inspection of the Walt Whitman Bridge.', ARRAY['Walt Whitman Bridge', 'biennial inspection', 'sub-consultant']),
('Portfolio', '/portfolio', 'project', 'Benjamin Franklin Bridge Biennial Inspection (2004, 2006, 2008 & 2010)', 'LSEA, as a sub-consultant, performed a biennial inspection of the Benjamin Franklin Bridge, which carries a high speed PATCO rail line along each fascia.', ARRAY['Benjamin Franklin Bridge', 'biennial inspection', 'PATCO rail', 'high speed rail']),
('Portfolio', '/portfolio', 'project', 'JFK Condition Survey of WTC Memorial (2017)', 'LSEA performed condition survey inspections of the WTC memorial site, including both pools, the WTC Memorial Building, and the tunnels underneath the site.', ARRAY['JFK', 'WTC Memorial', 'condition survey', 'memorial site', 'tunnels']),
('Portfolio', '/portfolio', 'project', 'Essex County Resources Recovery facility Condition Survey (2012)', 'LSEA provided the structural building condition survey for the Essex County Resource Recovery facility.', ARRAY['Essex County', 'Resource Recovery', 'condition survey', 'structural building']),
('Portfolio', '/portfolio', 'project', 'Teterboro Airport Condition Inspection (2011)', 'LSEA performed condition inspection on 7 buildings within Teterboro Airport, including office buildings, hangers, the tower, and the museum.', ARRAY['Teterboro Airport', 'condition inspection', 'airport buildings', 'hangers', 'tower', 'museum']),
('Portfolio', '/portfolio', 'project', 'Undergrade Bridge Inspection, Groups: B, E and F (2015-2016)', 'LSEA provided a team of 3 engineers for the in-depth hands-on undergrade bridge inspections for 3 projects.', ARRAY['undergrade bridge', 'inspection', 'NJ Transit', 'hands-on inspection']),
('Portfolio', '/portfolio', 'project', 'Rehabilitation of Raritan Drawbridge (2015)', 'LSEA was involved in the rehabilitation of the Raritan Drawbridge, which was severely damaged during Hurricane Sandy.', ARRAY['Raritan Drawbridge', 'rehabilitation', 'Hurricane Sandy', 'storm damage']),
('Portfolio', '/portfolio', 'project', 'Aberdeen-Matawan Park & Ride Parking Study (2007)', 'LSEA was involved in the planning and study of the parking lot for the Aberdeen-Matawan station for NJ TRANSIT.', ARRAY['Aberdeen-Matawan', 'Park & Ride', 'parking study', 'NJ TRANSIT', 'station planning']),

-- Partners Page Content
('Partners', '/partners', 'hero', 'Our Partners', 'Strategic partnerships driving innovation and excellence in engineering', ARRAY['partners', 'strategic partnerships', 'innovation', 'collaboration']),
('Partners', '/partners', 'partnership_overview', 'Strategic Partnerships', 'We collaborate with industry leaders to deliver exceptional results and drive innovation together. Our partnerships are built on shared values of excellence, innovation, and mutual success.', ARRAY['strategic partnerships', 'industry leaders', 'collaboration', 'shared values', 'excellence', 'innovation', 'mutual success']),
('Partners', '/partners', 'partner', 'Y Bird Airways', 'Leading aviation services provider with comprehensive flight operations and aircraft maintenance solutions across the northeast region. Services include Aircraft Maintenance, Flight Operations, Ground Support.', ARRAY['Y Bird Airways', 'aviation services', 'flight operations', 'aircraft maintenance', 'northeast region', 'ground support']),
('Partners', '/partners', 'partner', 'WOW Design', 'Creative design agency specializing in brand identity, digital experiences, and innovative marketing solutions for modern businesses. Services include Brand Identity, Web Design, Digital Marketing.', ARRAY['WOW Design', 'creative design', 'brand identity', 'digital experiences', 'marketing solutions', 'web design', 'digital marketing']),

-- Offices Page Content
('Offices', '/offices', 'hero', 'Our Offices', 'Strategic office locations across multiple states to serve our clients', ARRAY['offices', 'locations', 'multiple states', 'client service']),
('Offices', '/offices', 'office', 'Montville, New Jersey Office', 'Headquarters location at 150 River Road, Suite E2, Montville, New Jersey. Phone: (973) 588-3122, Email: info@lseacorp.com', ARRAY['Montville', 'New Jersey', 'headquarters', '150 River Road', 'NJ office']),
('Offices', '/offices', 'office', 'Cherry Hill, New Jersey Office', 'Located at 1101 North Kings Highway, Suite 311, Cherry Hill, New Jersey. Phone: (856) 330-4613, Email: info@lseacorp.com', ARRAY['Cherry Hill', 'New Jersey', 'North Kings Highway', 'NJ office']),
('Offices', '/offices', 'office', 'New York Office', 'Located at 1350 6th Avenue, West 55th Street, 3rd Floor, New York. Phone: (973) 588-3123, Email: info@lseacorp.com', ARRAY['New York', 'Manhattan', '6th Avenue', '55th Street', 'NY office']),
('Offices', '/offices', 'office', 'Long Island, New York Office', 'Located at 513 Valley Lane, Valley Stream, New York. Phone: (973) 588-3122, Email: info@lseacorp.com', ARRAY['Long Island', 'Valley Stream', 'New York', 'Valley Lane', 'NY office']),
('Offices', '/offices', 'office', 'Pennsylvania Office', 'Located at 228 Moore Street, Philadelphia, Pennsylvania. Phone: (267) 273-4769, Email: info@lseacorp.com', ARRAY['Pennsylvania', 'Philadelphia', 'Moore Street', 'PA office']),
('Offices', '/offices', 'office', 'Connecticut Office', 'Located at 120 Kane Street, Suite C8, West Hartford, Connecticut. Phone: (203) 314 5770, Email: info@lseacorp.com', ARRAY['Connecticut', 'West Hartford', 'Kane Street', 'CT office']),

-- Careers Page Content
('Careers', '/careers', 'hero', 'Careers', 'Join our team of engineering professionals and make a meaningful impact', ARRAY['careers', 'jobs', 'engineering professionals', 'employment']),
('Careers', '/careers', 'overview', 'Join Our Team', 'At LSEA Corporation, we''re always looking for talented professionals who share our commitment to excellence. Join a team where your expertise is valued, your growth is supported, and your contributions make a meaningful impact on communities worldwide.', ARRAY['join team', 'talented professionals', 'commitment to excellence', 'expertise valued', 'professional growth', 'meaningful impact', 'communities']),
('Careers', '/careers', 'job', 'Construction Inspectors', 'Full-time position in Montville, NJ. Requirements: 3+ years experience, NICET Levels I-IV Certified, ACI concrete technician, SAT asphalt pavement construction certification, NJDOT/NYSDOT/NJTA experience preferred.', ARRAY['Construction Inspectors', 'Montville NJ', 'NICET certified', 'ACI concrete', 'SAT asphalt', 'NJDOT', 'NYSDOT', 'NJTA']),
('Careers', '/careers', 'job', 'CADD Technician', 'Full-time position in Montville, NJ. Requirements: Experience in MicroStation and AutoCAD, NJDOT/NYSDOT/NJTA experience preferred.', ARRAY['CADD Technician', 'Montville NJ', 'MicroStation', 'AutoCAD', 'NJDOT', 'NYSDOT', 'NJTA']),
('Careers', '/careers', 'job', 'Building & Bridge Engineer', 'Full-time position in NJ/NY. Requirements: BSCE, 5+ years experience in Bridge or Building Design and Rehab, Familiarity with AASHTO, ACI & Steel manual, NJDOT/NYSDOT/PANYNJ/NJTA experience preferred, P.E. in NY/NJ/PA preferred.', ARRAY['Building Engineer', 'Bridge Engineer', 'BSCE', 'bridge design', 'building design', 'rehabilitation', 'AASHTO', 'ACI', 'Steel manual', 'PE license']),
('Careers', '/careers', 'job', 'Bridge Inspection Team Leaders & Assistant Team Leaders', 'Full-time position in NJ/NY. Requirements: BSc in Civil Engineering, P.E. in NY/NJ/PA/CT Preferred, 5+ years NYDOT/NJDOT/PANYNJ Bridge Inspection experience preferred, NHI/NYSDOT Training certificates preferred.', ARRAY['Bridge Inspection', 'Team Leaders', 'Civil Engineering', 'PE license', 'NYDOT', 'NJDOT', 'PANYNJ', 'NHI training', 'NYSDOT training']),
('Careers', '/careers', 'job', 'Structural Engineer', 'Full-time position in Montville, NJ. Requirements: BSc in Structural Engineering or Civil Engineering, 3+ years NJDOT/PANYNJ Bridge Inspection experience preferred, Analysis for innovative material implementation, self-healing concrete application, load rate analysis.', ARRAY['Structural Engineer', 'Montville NJ', 'Structural Engineering', 'Civil Engineering', 'bridge inspection', 'innovative materials', 'self-healing concrete', 'load rate analysis']),

-- Contact Page Content
('Contact', '/contact', 'hero', 'Contact Us', 'Get in touch with LSEA Corporation for your engineering needs', ARRAY['contact', 'get in touch', 'engineering needs', 'contact us']),
('Contact', '/contact', 'contact_form', 'Get in Touch', 'Contact form for inquiries and project discussions', ARRAY['contact form', 'inquiries', 'project discussions', 'get in touch']),
('Contact', '/contact', 'headquarters', 'Headquarters', 'Main office located at 150 River Road, Suite E2, Montville, NJ 07045', ARRAY['headquarters', 'main office', '150 River Road', 'Montville', 'NJ 07045']),
('Contact', '/contact', 'contact_phone', 'Phone', 'Main: (973) 588-3122, Fax: (973) 588-3123', ARRAY['phone', 'main phone', 'fax', '973-588-3122', '973-588-3123']),
('Contact', '/contact', 'contact_email', 'Email', 'General: info@lseacorp.com, Projects: kimlaw@lseacorp.com', ARRAY['email', 'general email', 'projects email', 'info@lseacorp.com', 'kimlaw@lseacorp.com']),
('Contact', '/contact', 'business_hours', 'Business Hours', 'Monday - Friday: 9:00 AM - 5:00 PM EST, Saturday: 9:00 AM - 2:00 PM EST, Sunday: Closed', ARRAY['business hours', 'Monday Friday', '9AM 5PM', 'Saturday', '9AM 2PM', 'Sunday closed', 'EST']),

-- Clients Page Content
('Clients', '/clients', 'hero', 'Our Clients', 'Trusted by leading organizations and government agencies', ARRAY['clients', 'trusted organizations', 'government agencies', 'partnerships']),
('Clients', '/clients', 'overview', 'Trusted by Leading Organizations', 'We are proud to work with government agencies, transportation authorities, and organizations that shape the infrastructure of tomorrow. Our partnerships are built on trust, excellence, and a shared commitment to public service.', ARRAY['trusted organizations', 'government agencies', 'transportation authorities', 'infrastructure', 'trust', 'excellence', 'public service']),
('Clients', '/clients', 'client', 'The Port Authority of New York and New Jersey', 'Bistate agency managing transportation infrastructure, including airports, bridges, tunnels, ports, and World Trade Center.', ARRAY['Port Authority', 'New York', 'New Jersey', 'PANYNJ', 'transportation infrastructure', 'airports', 'bridges', 'tunnels', 'ports', 'World Trade Center']),
('Clients', '/clients', 'client', 'New Jersey Department of Transportation', 'State agency overseeing New Jersey''s transportation systems, including planning, engineering, maintenance, and transit.', ARRAY['NJDOT', 'New Jersey Department of Transportation', 'transportation systems', 'planning', 'engineering', 'maintenance', 'transit']),
('Clients', '/clients', 'client', 'New Jersey Turnpike Authority', 'Agency managing New Jersey Turnpike and GSP, overseeing toll collection, maintenance, and roadway improvements.', ARRAY['NJTA', 'New Jersey Turnpike Authority', 'Turnpike', 'GSP', 'Garden State Parkway', 'toll collection', 'maintenance', 'roadway improvements']),
('Clients', '/clients', 'client', 'NJ Transit', 'Public transportation agency operating buses, trains, and light rail across New Jersey and into New York.', ARRAY['NJ Transit', 'public transportation', 'buses', 'trains', 'light rail', 'New Jersey', 'New York']),
('Clients', '/clients', 'client', 'Delaware River Port Authority', 'Bistate agency managing bridges and public transit between New Jersey and Pennsylvania across the Delaware River.', ARRAY['DRPA', 'Delaware River Port Authority', 'bridges', 'public transit', 'New Jersey', 'Pennsylvania', 'Delaware River']),
('Clients', '/clients', 'client', 'Counties and Municipalities', 'Local governments managing roads, traffic, planning, and transportation services within specific counties and municipalities in NJ.', ARRAY['counties', 'municipalities', 'local government', 'roads', 'traffic', 'planning', 'transportation services', 'New Jersey']),
('Clients', '/clients', 'client', 'HUD/Housing Authorities', 'Agencies providing affordable housing, community development, and assistance programs to low-income residents.', ARRAY['HUD', 'Housing Authorities', 'affordable housing', 'community development', 'assistance programs', 'low-income residents']),

-- Privacy Policy and Terms of Use
('Privacy Policy', '/privacy-policy', 'document', 'Privacy Policy', 'LSEA Corporation privacy policy covering information collection, usage, sharing, data security, user rights, and contact information for privacy concerns.', ARRAY['privacy policy', 'information collection', 'data usage', 'data sharing', 'data security', 'user rights', 'privacy concerns']),
('Terms of Use', '/terms-of-use', 'document', 'Terms of Use', 'Terms of use for the LS Engineering Associates Corporation website, including acceptance, website usage, intellectual property, privacy, liability, and contact information.', ARRAY['terms of use', 'website usage', 'intellectual property', 'privacy', 'liability', 'legal terms', 'LS Engineering Associates']),

-- Sitemap
('Sitemap', '/sitemap', 'navigation', 'Sitemap', 'Complete site navigation and page structure for LSEA Corporation website', ARRAY['sitemap', 'navigation', 'site structure', 'page links']),

-- Additional detailed content for better search coverage
('General', '/', 'company_info', 'LSEA Corporation', 'LS Engineering Associates Corporation is a multi-discipline consulting engineering firm providing bridge inspection, structural engineering, civil engineering, MEP engineering, architecture, land surveying, traffic engineering, and construction management services.', ARRAY['LS Engineering Associates', 'LSEA Corporation', 'consulting engineering', 'multi-discipline', 'bridge inspection', 'structural engineering', 'civil engineering', 'MEP engineering', 'architecture', 'land surveying', 'traffic engineering', 'construction management']),

-- Service Detail Keywords
('Services', '/services', 'keywords', 'Engineering Services Keywords', 'Bridge inspection services, structural assessment, building evaluation, civil engineering design, MEP systems, mechanical engineering, electrical engineering, plumbing design, HVAC systems, site development, highway design, roadway engineering, traffic analysis, transportation planning, land surveying, topographic surveys, construction inspection, project management, infrastructure development, rehabilitation projects, seismic analysis, load rating, condition assessment, feasibility studies, construction documents, permit applications, code compliance, safety evaluations', ARRAY['bridge inspection services', 'structural assessment', 'building evaluation', 'civil engineering design', 'MEP systems', 'mechanical engineering', 'electrical engineering', 'plumbing design', 'HVAC systems', 'site development', 'highway design', 'roadway engineering', 'traffic analysis', 'transportation planning', 'land surveying', 'topographic surveys', 'construction inspection', 'project management', 'infrastructure development', 'rehabilitation projects', 'seismic analysis', 'load rating', 'condition assessment', 'feasibility studies', 'construction documents', 'permit applications', 'code compliance', 'safety evaluations']),

-- Geographic Coverage
('Geographic Coverage', '/', 'locations', 'Service Areas', 'LSEA Corporation serves clients throughout New Jersey, New York, Pennsylvania, Connecticut, and the greater Northeast region with offices in Montville NJ, Cherry Hill NJ, New York NY, Valley Stream NY, Philadelphia PA, and West Hartford CT.', ARRAY['New Jersey', 'New York', 'Pennsylvania', 'Connecticut', 'Northeast region', 'Montville', 'Cherry Hill', 'Manhattan', 'Valley Stream', 'Philadelphia', 'West Hartford', 'NJ', 'NY', 'PA', 'CT', 'service areas', 'regional coverage']);