// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgnxlvqarqqstoijqvqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbnhsdnFhcnFxc3RvaWpxdnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODAzODEsImV4cCI6MjA2Njk1NjM4MX0.iWZYrycXFob9778b7snB487GRIBuqt59ODjdb2Hlur8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});